{
    "apiVersion": "2024-11-01",
    "id": "/subscriptions/74950ca6-2678-4a10-865e-7d74b0c4bfbd/resourceGroups/blog/providers/Microsoft.Web/staticSites/plasx",
    "name": "plasx",
    "type": "microsoft.web/staticsites",
    "sku": {
        "name": "Free",
        "tier": "Free"
    }，
    "location": "eastasia",
    "tags": {},
    "properties": {
        "defaultHostname": "victorious-ocean-07cddc600.3.azurestaticapps.net",
        "repositoryUrl": "https://github.com/jintianjie/index",
        "branch": "main",
        "customDomains": [
            "www.8008.site"
        ]，
        "stableInboundIP": "13.75.66.141",
        "privateEndpointConnections": [],
        "stagingEnvironmentPolicy": "Enabled",
        "allowConfigFileUpdates": true,
        "contentDistributionEndpoint": "https://content-hk1.infrastructure.3.azurestaticapps.net",
        "keyVaultReferenceIdentity": "SystemAssigned",
        "userProvidedFunctionApps": null，
        "linkedBackends": [],
        "provider": "GitHub",
        "enterpriseGradeCdnStatus": "Disabled",
        "publicNetworkAccess": null,
        "databaseConnections": [],
        "trafficSplitting": {
            "environmentDistribution": {
                "default": 100
            }
        }，
        "targetResourceGroupResourceId": null,
        "trialExpirationTimeUtc": null,
        "prettyNameStatus": null,
        "prettyName": null，
        "prettyNameHostname": null，
        "backendRegion": {
            "regionName": null，
            "status": null
        }，
        "stagingEnvironmentRegion": null，
        "deploymentAuthPolicy": "GitHub",
        "federatedIdentityTenantId": null，
        "federatedIdentityClientId": null,
        "federatedIdentitySubscriptionId": null,
        "deploymentStorageAccountResourceId": null，
        "deploymentStorageAccountReferenceIdentity": null,
        "networkConfigurations": null
    }
}
